Styling Leaderboard
carreraprogrammer/Leaderboard pull request #3
Opened 2022-10-21 20:42 UTC by carreraprogrammer

In this branch, I improve the look and feel of the application

2022-10-21 20:48 UTC, zainsadaqat requested changes
# INVALID ❌ ❌ ❌
# Hello @carreraprogrammer 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have not attached the linters required for this project. Please attach the required linters and submit it for review again. 👍🏻 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

<img src="https://media4.giphy.com/media/DN1I1TGhL83cNx9DSR/giphy.gif"/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-21 22:06 UTC, ichala requested changes
Hi  @carreraprogrammer 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Great Design✔️ 
- No linters Errors ✔️

 ## Required Changes ♻️

- [ ] 🛑  Kindly Update the readme file to make it more professional by following these steps :

1. kindly update the setup, install & Getting Started sections where you guide the user on how to clone your application, how to install it, and how to run it locally 
2. kindly update your live demo link if you have one or remove the section
3. kindly remove any unused sections in your readme file
4. your  MIT Licence link is broken , kindly try to fix it and update it

- [ ] 🛑  You have some errors in your application kindly try to fix them :

![image](https://user-images.githubusercontent.com/89282221/197295388-2040edc0-3139-4d4c-8645-644884b8d259.png)


- [ ] 🛑  **_Check The comments below_**



## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-21 22:06 UTC, ichala commented on src/modules/game.js
> +// Game
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the eslint disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/modules/display-scores.js
> +/* eslint-disable linebreak-style */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/modules/add-score.js
> +/* eslint-disable linebreak-style */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/index.js
> +/* eslint-disable linebreak-style */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/modules/leaderboard-API.js
> +/* eslint-disable linebreak-style */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/style.css
> +/* stylelint-disable length-zero-no-unit */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-21 22:06 UTC, ichala commented on src/style.css
> +  /* stylelint-disable-next-line csstree/validator */
- [ ]  linter is used to flag programming errors, bugs, stylistic errors, and suspicious constructs, so to keep your code readable and understandable by everyone, kindly remove the linters disabling command and please fix all the linters error 🙏

2022-10-22 01:13 UTC, MahmoudBakr23 approved these changes
Hi @carreraprogrammer 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done making the required changes the previous reviewer

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 22:33 UTC, merged